
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : expression TIMES termexpression : expression DIVIDE termexpression : termterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'RPAREN':([1,2,4,6,11,12,13,14,15,],[-5,-7,-6,11,-8,-4,-3,-1,-2,]),'DIVIDE':([1,2,4,5,6,11,12,13,14,15,],[-5,-7,-6,7,7,-8,-4,-3,-1,-2,]),'NUMBER':([0,3,7,8,9,10,],[2,2,2,2,2,2,]),'TIMES':([1,2,4,5,6,11,12,13,14,15,],[-5,-7,-6,8,8,-8,-4,-3,-1,-2,]),'PLUS':([1,2,4,5,6,11,12,13,14,15,],[-5,-7,-6,9,9,-8,-4,-3,-1,-2,]),'LPAREN':([0,3,7,8,9,10,],[3,3,3,3,3,3,]),'MINUS':([1,2,4,5,6,11,12,13,14,15,],[-5,-7,-6,10,10,-8,-4,-3,-1,-2,]),'$end':([1,2,4,5,11,12,13,14,15,],[-5,-7,-6,0,-8,-4,-3,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,3,7,8,9,10,],[1,1,12,13,14,15,]),'expression':([0,3,],[5,6,]),'factor':([0,3,7,8,9,10,],[4,4,4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser_rules.py',5),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser_rules.py',9),
  ('expression -> expression TIMES term','expression',3,'p_expression_times','parser_rules.py',13),
  ('expression -> expression DIVIDE term','expression',3,'p_expression_divide','parser_rules.py',17),
  ('expression -> term','expression',1,'p_expression_term','parser_rules.py',21),
  ('term -> factor','term',1,'p_term_factor','parser_rules.py',25),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser_rules.py',29),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser_rules.py',33),
]
